import React from 'react';
import { MetricCard } from './velocity-guide';

export function ExecutiveBriefGuide() {
    return (
        <div className="space-y-12 pb-16">
            {/* 1. Orientation Summary */}
            <div className="space-y-4">
                <p className="text-lg text-slate-300 leading-relaxed font-light">
                    The <strong>Executive Brief</strong> dashboard provides a 10,000-foot view of facility health tailored specifically for VP-level leadership and Site Directors.
                </p>
                <p className="text-slate-400">
                    While other dashboards dive deep into individual associate metrics or forensic anomalies, the Executive Brief strips away the noise. It answers the fundamental operational questions: <em>"Where did my building bleed money today, was my throughput healthy, and can I trust this data?"</em>
                </p>
                <p className="text-slate-400">
                    Below is the exact mathematical breakdown of how the engine calculates the four high-level leadership pillars.
                </p>
            </div>

            <hr className="border-slate-800" />

            {/* 2. The Four Pillars Section */}
            <div className="space-y-10">
                <h3 className="text-2xl font-semibold text-white mb-6">The Four Leadership Pillars</h3>

                {/* Pillar 1 */}
                <div className="bg-slate-900/50 p-6 rounded-xl border border-rose-500/20 shadow-lg">
                    <h4 className="text-xl font-bold text-rose-400 flex items-center gap-2 mb-3 border-b border-rose-500/20 pb-4">
                        <span className="material-symbols-outlined text-2xl">payments</span>
                        Pillar 1: Financial Friction (Payroll Waste)
                    </h4>
                    <p className="text-slate-300 mb-6 bg-slate-950 p-4 rounded border border-slate-800">
                        Quantifies the exact payroll waste generated by operational inactivity. Rather than just showing "idle hours," this pillar translates hours into actual dollars lost based on the global hourly wage setting.
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                        <MetricCard
                            title="Total Hours Lost (Net Gap)"
                            scope="Aggregate Shift Context"
                            direction="Lower is Better"
                            color="rose"
                            formula="∑ (Task Sequence Net Gaps &gt; Allowable Threshold)"
                            description="The absolute total of all undocumented downtime across every worker in the dataset. If a worker is clocked in but not scanning, they accumulate Net Gaps."
                            example={{
                                scenario: "Worker A finishes a task at 10:00 AM. Their next task starts at 10:15 AM. The 'Net Gap' is 15 minutes. If the Allowable Threshold is 5 minutes, this 15-minute gap is captured and added to the Total Hours Lost bucket.",
                                math: "Net Gap (15m) > Threshold (5m) = 0.25 Hours Lost added to total."
                            }}
                        />
                        <MetricCard
                            title="Financial Bleed"
                            scope="Site Payload"
                            direction="Lower is Better"
                            color="rose"
                            formula="Total Hours Lost × Default Hourly Wage ($)"
                            description="Projected payroll dollars spent on associates who were technically clocked-in but operationally inactive."
                            example={{
                                scenario: "The engine compiled exactly 145 Hours of Lost Time across 80 agents over the shift. The system's Global Shift Parameters set the Hourly Wage to $22.00.",
                                math: "145 Hours Lost × $22/hr Wage = $3,190.00 Financial Bleed."
                            }}
                        />
                    </div>

                    {/* Explainer Box */}
                    <div className="bg-rose-950/20 border border-rose-500/30 rounded-lg p-5">
                        <h5 className="font-bold text-rose-300 mb-2 flex items-center gap-2">
                            <span className="material-symbols-outlined text-sm">science</span>
                            Deep Dive: Variables & Assumptions
                        </h5>
                        <ul className="text-sm text-slate-300 space-y-3">
                            <li><strong className="text-rose-400">Task Sequence Net Gap:</strong> This is the chronological white-space between two tasks. <code>Timestamp of TASK_B_START - Timestamp of TASK_A_END</code>.</li>
                            <li><strong className="text-rose-400">Allowable Threshold:</strong> Sourced from <code>Config.BreakThresholdMinutes</code> (usually set to 5 minutes). We <em>assume</em> gaps under 5 minutes are just walking/bathroom/water breaks. Only gaps exceeding this threshold are flagged as true structural waste.</li>
                            <li><strong className="text-rose-400">Default Hourly Wage:</strong> Sourced dynamically from <code>Config.engineeredStandards.hourlyWage</code>. This is globally configurable via the Settings &gt; Global Shift Parameters page.</li>
                        </ul>
                    </div>
                </div>

                {/* Pillar 2 */}
                <div className="bg-slate-900/50 p-6 rounded-xl border border-indigo-500/20 shadow-lg">
                    <h4 className="text-xl font-bold text-indigo-400 flex items-center gap-2 mb-3 border-b border-indigo-500/20 pb-4">
                        <span className="material-symbols-outlined text-2xl">speed</span>
                        Pillar 2: Shift Throughput & Bottlenecks
                    </h4>
                    <p className="text-slate-300 mb-6 bg-slate-950 p-4 rounded border border-slate-800">
                        A Theory of Constraints (ToC) abstraction detailing system velocity. It blends the entire facility's output into a single 'Master Score' and automatically detects workflow bottlenecks.
                    </p>

                    <div className="grid grid-cols-1 gap-6 mb-6">
                        <MetricCard
                            title="Master Norm Score"
                            scope="Global Warehouse Engine"
                            direction="Higher is Better"
                            color="emerald"
                            formula="∑ (Volume in Pick + Sort + Pack) / ∑ (Filtered Operational Time across all roles)"
                            description="The true blended Units Per Hour (UPH) across all active paths. Unlike simple volume counting, the Master Score normalizes the effort so a Picker's time and a Packer's time weigh equally against facility output."
                            example={{
                                scenario: "The building picked 10K units, sorted 8K, and packed 5K. The algorithm looks at the 'Active Wall Clock Time' (excluding breaks) for every associate, sums it up, and calculates the blended rate.",
                                math: "(10K + 8K + 5K) Output / Total 200 Active Hours = 115 Master UPH."
                            }}
                        />

                        <div className="bg-slate-800/50 p-5 rounded-xl border border-slate-700">
                            <h5 className="font-bold text-indigo-300 mb-3 flex items-center gap-2">
                                <span className="material-symbols-outlined">account_tree</span>
                                Algorithmic Bottleneck Indicator (Volume Funnel)
                            </h5>
                            <p className="text-sm text-slate-300 mb-4">
                                Because different phases have different natural Unit Process Times (e.g. packing always takes longer than picking), the engine uses absolute <strong>Phase Volume</strong> instead of UPH to find the constraint. It compares total units processed by each phase.
                            </p>
                            <div className="bg-black/50 p-4 rounded-lg font-mono text-sm border border-slate-800 space-y-2">
                                <p className="text-slate-500">// Example Engine Logic</p>
                                <p className="text-emerald-400">Pick_Volume = 10,000 units</p>
                                <p className="text-emerald-400">Sort_Volume = 8,000 units</p>
                                <p className="text-rose-400">Pack_Volume = 6,000 units  <span className="text-slate-500">&lt;-- Minimum Value (Constraint)</span></p>
                                <p className="text-amber-500 mt-2">output = "Packing is the primary constraint today, processing 40% less volume than Picking (10,000 vs 6,000)."</p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Pillar 3 */}
                <div className="bg-slate-900/50 p-6 rounded-xl border border-emerald-500/20 shadow-lg">
                    <h4 className="text-xl font-bold text-emerald-400 flex items-center gap-2 mb-3 border-b border-emerald-500/20 pb-4">
                        <span className="material-symbols-outlined text-2xl">auto_awesome</span>
                        Pillar 3: AI System Utilization
                    </h4>
                    <p className="text-slate-300 mb-6 bg-slate-950 p-4 rounded border border-slate-800">
                        Tracks whether the facility is actually adopting the advanced algorithmic batching provided by the AI, or if supervisors are continuing to manually drop unoptimized wave structures.
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                        <MetricCard
                            title="Adaptation Index Score"
                            scope="Algorithm Usage"
                            direction="Higher is Better"
                            color="emerald"
                            formula="∑ (Volume Percent × Profile Weight)"
                            description="A 0.0 to 10.0 scale reflecting how much volume was processed through advanced flow profiles (Put-to-Wall, Mixed Singles) instead of basic manual single-order picks. Target > 6.0."
                            example={{
                                scenario: "If 80% of volume was batched into 'Put-to-Wall' (Weight: 7) and 20% ran as normal 'Order Based' (Weight: 1).",
                                math: "(0.80 × 7) + (0.20 × 1) = 5.8 Adaptation Index."
                            }}
                        />
                        <MetricCard
                            title="AI Order Penetration (%)"
                            scope="Manual Override Tracking"
                            direction="Higher is Better"
                            color="slate"
                            formula="(Total Orders - Manually Assigned Orders) / Total Orders"
                            description="Measures the raw percentage of orders originating straight from the AI integration layer compared to orders manually built or assigned by floor supervisors."
                            example={{
                                scenario: "Out of 5,000 total shift orders, 50 were manually built by a manager on the floor to clear a specific dock door.",
                                math: "4,950 / 5,000 = 99.0% AI Order Penetration."
                            }}
                        />
                    </div>
                </div>

                {/* Pillar 4 */}
                <div className="bg-slate-900/50 p-6 rounded-xl border border-blue-500/20 shadow-lg">
                    <h4 className="text-xl font-bold text-blue-400 flex items-center gap-2 mb-3 border-b border-blue-500/20 pb-4">
                        <span className="material-symbols-outlined text-2xl">pie_chart</span>
                        Pillar 4: Workforce Allocation Map
                    </h4>
                    <p className="text-slate-300 mb-6 bg-slate-950 p-4 rounded border border-slate-800">
                        A Donut Chart mapping the exact distribution of labor hours.
                    </p>

                    <ul className="text-sm text-slate-300 space-y-4 pl-4 list-disc marker:text-blue-500">
                        <li>
                            <strong className="text-white">Active Phases (Pick, Sort, Pack):</strong> The engine sums the exact timeline durations of all tasks categorized correctly via the Job Dictionary. Time is assigned definitively to one phase.
                        </li>
                        <li>
                            <strong className="text-rose-400">The Inactivity Wedge:</strong> The graph explicitly injects the "Total Hours Lost" (from Pillar 1) as its own wedge next to the productive phases. This forces leadership to visually weigh "Time working" against "Time doing nothing."
                        </li>
                    </ul>
                </div>
            </div>

            {/* 3. Actionable Actions */}
            <div className="space-y-6">
                <hr className="border-slate-800 my-8" />
                <h3 className="text-2xl font-semibold text-white mb-4">Driving Actions from the Brief</h3>
                <p className="text-slate-400 mb-6 max-w-4xl">
                    How leadership should use this summary to prescribe deep-dives for their subordinate operators.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="bg-slate-900/50 p-6 rounded-xl border border-rose-500/20 shadow-md">
                        <div className="w-10 h-10 rounded-lg bg-rose-500/20 text-rose-400 flex items-center justify-center font-bold text-lg mb-4">1</div>
                        <h4 className="font-bold text-white text-base mb-2">High Financial Bleed?</h4>
                        <p className="text-sm text-slate-400">If Pillar 1 shows significant $ waste, instruct the floor manager to open the <strong className="text-indigo-400">Employee Performance</strong> dashboard and sort the roster by Utilization to coach or re-assign the bottom 10%.</p>
                    </div>
                    <div className="bg-slate-900/50 p-6 rounded-xl border border-emerald-500/20 shadow-md">
                        <div className="w-10 h-10 rounded-lg bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold text-lg mb-4">2</div>
                        <h4 className="font-bold text-white text-base mb-2">Low AI Utilization?</h4>
                        <p className="text-sm text-slate-400">If Pillar 3 shows a low Adaptation Index, instruct supervisors to open the <strong className="text-emerald-400">Adaptation Insights</strong> dashboard to see which advanced flow profiles (like Put-to-Wall or Multi-Item batching) are being manually sidestepped.</p>
                    </div>
                    <div className="bg-slate-900/50 p-6 rounded-xl border border-indigo-500/20 shadow-md">
                        <div className="w-10 h-10 rounded-lg bg-indigo-500/20 text-indigo-400 flex items-center justify-center font-bold text-lg mb-4">3</div>
                        <h4 className="font-bold text-white text-base mb-2">Severe Bottlenecking?</h4>
                        <p className="text-sm text-slate-400">If Pillar 2 flags a specific phase (e.g. Packing), check the <strong className="text-blue-400">Adaptation Insights</strong> tab to see if physical parameters (like box sizes or wave density) changed unexpectedly.</p>
                    </div>
                </div>
            </div>
        </div>
    );
}
